name: amc
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchaudio
      - torchvision
      - numpy
      - scipy
      - pandas
      - scikit-learn
      - librosa
      - soundfile
      - tqdm
      - matplotlib
      - pyyaml
